name: Build Runtime
# on:
#   push:
#     tags:
#       - '*'
on: [push]
jobs:
  windows-build:
    name: windows-build
    runs-on: windows-latest
    steps:
      - uses: mxschmitt/action-tmate@v3
      # - uses: actions/checkout@v3
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.8"
      # - run: "pip install -r requirements.txt"
      # - run: |
      #     pyinstaller index.py `
      #       --collect-data sv_ttk `
      #       --add-data="./gui/assets/*.png;./gui/assets/" `
      #       --add-data="./quick_convert_data/docx/*;./quick_convert_data/docx/" `
      #       --add-data="./quick_convert_data/renpy/*;./quick_convert_data/renpy/" `
      #       --name doc_to_renpy
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: doc_to_renpy-windows-${{env.branch_name}}
      #     path: dist/
      #     retention-days: 2
  # linux-build:
  #   name: linux-build
  #   runs-on: ubuntu-latest
  #   env:
  #     branch_name: ${{ echo "${github.ref_name//[\/]/-}" }}
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.8"
  #     - run: "pip install -r requirements.txt"
  #     - run: |
  #         pyinstaller index.py \
  #           --collect-data sv_ttk \
  #           --add-data="./gui/assets/*.png:./gui/assets/" \
  #           --add-data="./quick_convert_data/docx/*:./quick_convert_data/docx/" \
  #           --add-data="./quick_convert_data/renpy/*:./quick_convert_data/renpy/" \
  #           --name doc_to_renpy
  #     - run: |
  #         echo ""
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: doc_to_renpy-linux-${{env.branch_name}}
  #         path: dist/
  #         retention-days: 2