name: Build Runtime
on: workflow_dispatch
jobs:
  windows-build:
    name: windows-build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: "pip install -r requirements.txt"
      - run: |
          pyinstaller index.py `
            --collect-data sv_ttk `
            --add-data="./gui/assets/*.png;./gui/assets/" `
            --add-data="./quick_convert_data/docx/*;./quick_convert_data/docx/" `
            --add-data="./quick_convert_data/renpy/*;./quick_convert_data/renpy/" `
            --windowed `
            --name doc_to_renpy
      - run: | 
          $local_ref_name="${{github.ref_name}}"
          $branch_name=$local_ref_name.replace("/", "-")
          echo "BUILD_VERSION=$branch_name" >> $env:GITHUB_ENV
      - run: |
          Compress-Archive ./dist ./doc_to_renpy-windows-${{env.BUILD_VERSION}}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: doc_to_renpy-windows-${{env.BUILD_VERSION}}
          path: doc_to_renpy-windows-${{env.BUILD_VERSION}}.zip
          retention-days: 2
  linux-build:
    name: linux-build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: "pip install -r requirements.txt"
      - run: |
          pyinstaller index.py \
            --collect-data sv_ttk \
            --add-data="./gui/assets/*.png:./gui/assets/" \
            --add-data="./quick_convert_data/docx/*:./quick_convert_data/docx/" \
            --add-data="./quick_convert_data/renpy/*:./quick_convert_data/renpy/" \
            --windowed \
            --name doc_to_renpy
      - run: | 
          local_ref_name="${{github.ref_name}}"
          # Take / in ref name and replace with -
          echo "BUILD_VERSION=${local_ref_name//[\/]/-}" >> $GITHUB_ENV
      - run: |
          tar -cvf doc_to_renpy-linux-${{env.BUILD_VERSION}}.tar.gz ./dist
      - uses: actions/upload-artifact@v4
        with:
          name: doc_to_renpy-linux-${{env.BUILD_VERSION}}
          path: doc_to_renpy-linux-${{env.BUILD_VERSION}}.tar.gz
          retention-days: 2
  mac-build:
    name: mac-build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: "pip install -r requirements.txt"
      - run: |
          pyinstaller index.py \
            --collect-data sv_ttk \
            --add-data="./gui/assets/*.png:./gui/assets/" \
            --add-data="./quick_convert_data/docx/*:./quick_convert_data/docx/" \
            --add-data="./quick_convert_data/renpy/*:./quick_convert_data/renpy/" \
            --windowed \
            --name doc_to_renpy
      - run: | 
          local_ref_name="${{github.ref_name}}"
          # Take / in ref name and replace with -
          echo "BUILD_VERSION=${local_ref_name//[\/]/-}" >> $GITHUB_ENV
      - run: |
          ditto -c -k --sequesterRsrc --keepParent ./dist doc_to_renpy-macos-${{env.BUILD_VERSION}}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: doc_to_renpy-macos-${{env.BUILD_VERSION}}
          path: doc_to_renpy-macos-${{env.BUILD_VERSION}}.zip
          retention-days: 2
